name: mobile
description: "CampusLink mobile app for students and teachers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6

  # State Management
  provider: ^6.1.5+1

  # Supabase backend
  supabase_flutter: ^2.9.0

  # File Handling & Opening
  file_picker: ^10.3.6
  flutter_downloader: ^1.11.4
  open_filex: ^4.3.3
  url_launcher: ^6.3.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
